#cloud-config

# include one or more SSH public keys
ssh_authorized_keys:
 - ssh-rsa AAAAB3NzaC1yc3EAAAADAQABAAABAQDTLW4dXtupE8jx4H0w845HocMtuOxfaXOLR27uDzQblwrLX22xH8aIxRMxnWh6iHvtUhmtYRxmwpY/Xm28F/NmaDLWweofB+aQNa1aABo9rfzEfQDtpZeoRUskqpxcOPlGvrjKIGA80qGyWh4MEAz/GbFhmVZ1hMneGNH+mHAsnxd2qgqhdQsStm0yHAiCEzEODKcNvQbk9YALChKddFZuDyxPic4RrPyfN3kiv4cEuTuxvj5ScQu1EQFU7e2SEjZMbY7MPMdajAYzzG9+2l0YEDX/oTSVba4g3tF/eqjUwqzHZojEfABE6NSEWzbIShbd58D/wnOLAXJk+MTMtR11 root@ubuntuBase
